### ISSUE TITLE
"No such file" error

### ISSUE THREAD

**Issue by wabiloo** [JNoDuq/videobench#1]
Hi,
I've been trying to run the tool with a couple of test output files (against an input file).
I've tried both with the UI and at command line.  I'm getting an error however:

```
python3 videobench.py -ref ~/Downloads/videobench_test/input.mxf -i ~/Downloads/videobench_test/test1.mp4 ~/Downloads/videobench_test/test2.h264

* Analyzing Reference File...
-> input.mxf
 Bitrate  : 50.01 Mbps
 r_framerate : 25.0
 interlaced : 1

* Analyzing tests Files...
-> test1.mp4
 Bitrate : 6.5 Mbps
 r_framerate : 50.0
 interlaced : 0
-> test2.h264
 Bitrate : 6.5 Mbps
 r_framerate : 50.0
 interlaced : 0

* Quality measures...

-> test1.mp4
 Reference deint_filter : auto
 VMAF Model : /usr/local/share/model/vmaf_v0.6.1.pkl
 Scale filter : scale=1920:1080:flags=neighbor
 Quality Subsampling : 1
 Calculate VMAF & PSNR (libvmaf)

-> test2.h264
 Reference deint_filter : auto
 VMAF Model : /usr/local/share/model/vmaf_v0.6.1.pkl
 Scale filter : scale=1920:1080:flags=neighbor
 Quality Subsampling : 1
 Calculate VMAF & PSNR (libvmaf)

Traceback (most recent call last):
  File "videobench.py", line 219, in <module>
    data_json = json.load(open("{0}quality_{1}.json".format( tmp_path , input_obj.name)))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/videobench/quality_test1.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "videobench.py", line 221, in <module>
    with open("{0}quality_{1}.json".format( tmp_path , input_obj.name), 'r') as file : #################### replace nan by 0
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/videobench/quality_test1.json'
```

I have checked the /tmp directory, and although I can see frames_* and packets_* JSON files for those files, I see no quality_* file

Any idea where the problem could be coming from?

**Comment by JNoDuq** [comment]
Hi,
It look like the quality measures are not made.
Is it possible to you to send me your files (FTP, wetransfer, ...) ?
It's the easiest way for me to try to reproduce and understand the problem.

**Comment by wabiloo** [comment]
Download URLs for the 3 files sent via Slack

**Comment by JNoDuq** [comment]
The problem was the detection of the deint filter, I have changed the way I do it by using avg_frame_rate instead of r_frame_rate

**Comment by dwonky** [comment]
Hi There,

I have just encountered this same issue with my VMAF running on a Linux Guest OS on virtual box. I'm getting the same error with it saying json not found.

how did you resolve? i can see you mentioned changing the de-interlacing filter but how is this done?
