### ISSUE TITLE
Result Window: All clickable UI elements are greyed-out 

### ISSUE THREAD

**Issue by n300home** [JNoDuq/videobench#14]
Hi,

many thanks for this really cool project. I'm going to using it to get visual idea of differences between encoders. In my case h264/65 vs. latest NVENC HW-Encoders. 
The analysis works fine as far as I can see. Output JSON get generated and result windows appears. But at this point I'm unable to click anything in UI. All elements are greyed out as you can see in attached screenshots.
![image](https://user-images.githubusercontent.com/25461480/81504078-aa457200-92e7-11ea-806b-4cdba972089c.png)

the only errors I can see are here in terminal:
![image](https://user-images.githubusercontent.com/25461480/81504150-ed9fe080-92e7-11ea-8439-85f03a47c976.png)

I'm running a fresh installed Ubuntu 18 LTS as VM.

Do you have any ideas what I'm doing wrong?

Many thanks in advance and best regards

**Comment by SebSonic1979** [comment]
After getting the tool running on Windows i have the same Problem with the same output at the command Line and also no clickable UI Elements. Any suggestion how to solve this would be appreciated.

**Comment by JJHW149** [comment]
Same problem here on Ubuntu 20.04

**Comment by SebSonic1979** [comment]
So, found a solution for this with my 20 year old school Java "skills". In videobench_ui.py you have to make all commands to comments for the Lines 509-519 by adding a # to the beginning of the Line that it looks like this: 	#self.barChart_vmaf.addAxis(self.axisX, QtCore.Qt.AlignBottom). When you edit the File with the tool IDLE the Line should change the color to red. To be honest it was just some try and error stuff, but in the end it works, at least under Windows10 but it should also work under Linux. Now all clickable UI Elements work.
