### ISSUE TITLE
Requirements from Netflix/VMAF have changed, Dockerfile needs to be updated

### ISSUE THREAD

**Issue by SebSonic1979** [JNoDuq/videobench#18]
You need to change the Dockerfile in Line 17 and add some new requirements, otherwise the Docker Container Creation fails.

      && pip install numpy scipy matplotlib notebook pandas sympy nose scikit-learn scikit-image h5py sureal dill cython PyWavelets meson \

For me the missing "cython" was the main Reason why Container fails, but i added all requirements, just to be safe.

**Comment by JJHW149** [comment]
@SebSonic1979 Thank you, I was stuck wondering why the container wouldn't finish building for me.

**Comment by gmk57** [comment]
On Linux Mint 19.3 I also had to add `RUN apt-get install -y nasm` near the beginning of `Dockerfile`.
Otherwise creating container failed with `libvmaf/src/meson.build:40:8: ERROR: Program 'nasm' not found`.

**Comment by JNoDuq** [comment]
Thank you for the dockerfile update. I have merged the commit
