### ISSUE TITLE
Feature Request: bigger graphs

### ISSUE THREAD

**Issue by wabiloo** [JNoDuq/videobench#2]
It would be great to be able to select one of the graphs and make them bigger (to see more details), either in the window or as a separate window - to be able to go into the detail, ideally also zoom on particular time ranges

**Comment by JNoDuq** [comment]
You can already set the size of the graph independently. 
You can change the size or to  fold of a graph.
Depending of your OS the handle are more or less visible.
Here is some exemples of what you can do.

![Capture d’écran 2019-06-11 à 09 53 59](https://user-images.githubusercontent.com/10562413/59255203-f26c9800-8c31-11e9-9f36-ed038f823ee0.png)

![Capture d’écran 2019-06-11 à 10 02 44](https://user-images.githubusercontent.com/10562413/59255220-f8627900-8c31-11e9-9e4c-05b1656c0b1d.png)

I will check if I can add a zoom function
